# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
print("a.sum()可指定以某一軸相加，而np.sum()和sum(a)不行")

a.sum()可指定以某一軸相加，而np.sum()和sum(a)不行


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [19]:
A = np.random.random((5, 5))
#print(A)
A_avg = np.mean(A)
A_std = np.std(A)
print((A-A_avg)/A_std)

[[ 1.18038642  0.57108326  1.05556176 -1.51311869  0.8855009 ]
 [ 1.06571725 -0.74305358 -1.14495827  0.31415884  1.18593751]
 [ 0.52307943 -1.21876644 -0.89201392 -1.58155464  0.43479279]
 [ 1.41061885 -0.34143666  0.50241382 -0.95363067 -1.54222889]
 [ 0.60827021  0.41933746  1.30321343 -0.38824325 -1.1410669 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [31]:
a = np.random.rand(10)
a[np.argmax(a)] = -1
print(a)

[ 0.84723036  0.38690162  0.82029541  0.26930163  0.20790401  0.04304204
 -1.          0.74932247  0.5092253   0.52408458]
