# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
print("a.sum()可指定以某一軸相加，而np.sum()和sum(a)不行")

a.sum()可指定以某一軸相加，而np.sum()和sum(a)不行


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
A = np.random.random((5, 5))
A = (A - A.min()) / (A.max() - A.min())
print(A)

[[0.45867291 0.34416013 0.         0.84045663 0.19055589]
 [0.33390203 0.49365057 1.         0.72022384 0.85135179]
 [0.84169889 0.37870976 0.48441971 0.05820718 0.8313231 ]
 [0.70043255 0.59700364 0.49550352 0.34149856 0.26086917]
 [0.98625753 0.5861515  0.45710114 0.14411486 0.52487274]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [31]:
a = np.random.rand(10)
a[np.argmax(a)] = -1
print(a)

[ 0.84723036  0.38690162  0.82029541  0.26930163  0.20790401  0.04304204
 -1.          0.74932247  0.5092253   0.52408458]
