# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [10]:
%timeit -n 10 a = 2

for column in Z:
    for row in column:
        for i in row:
            i +=1
Z

41.4 ns ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[   9,    7,    7, ...,    6,   10,    6],
        [   6,    4,    7, ...,    7,   10,   10],
        [  11,    5,    4, ...,   11,    9,    9],
        ...,
        [   3,    4,    2, ...,   11,    3,    7],
        [   2,    6,    7, ...,   11,    9,   11],
        [  11,    2,    2, ...,    8,    3,    2]],

       [[1967, 1962, 1969, ..., 1965, 1963, 1967],
        [1960, 1961, 1966, ..., 1966, 1960, 1963],
        [1965, 1964, 1966, ..., 1965, 1962, 1964],
        ...,
        [1960, 1966, 1965, ..., 1966, 1962, 1960],
        [1962, 1961, 1969, ..., 1967, 1966, 1966],
        [1965, 1968, 1963, ..., 1966, 1963, 1963]],

       [[1927, 1924, 1930, ..., 1927, 1929, 1929],
        [1924, 1926, 1928, ..., 1933, 1925, 1925],
        [1933, 1926, 1931, ..., 1925, 1932, 1927],
        ...,
        [1932, 1924, 1925, ..., 1924, 1930, 1925],
        [1928, 1931, 1933, ..., 1928, 1928, 1924],
        [1933, 1932, 1926, ..., 1924, 1931, 1924]],

       ...,

       [[   9,    4,   1

In [11]:
%timeit -n 10 a = 2

Z+1

32.9 ns ± 8.81 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[  10,    8,    8, ...,    7,   11,    7],
        [   7,    5,    8, ...,    8,   11,   11],
        [  12,    6,    5, ...,   12,   10,   10],
        ...,
        [   4,    5,    3, ...,   12,    4,    8],
        [   3,    7,    8, ...,   12,   10,   12],
        [  12,    3,    3, ...,    9,    4,    3]],

       [[1968, 1963, 1970, ..., 1966, 1964, 1968],
        [1961, 1962, 1967, ..., 1967, 1961, 1964],
        [1966, 1965, 1967, ..., 1966, 1963, 1965],
        ...,
        [1961, 1967, 1966, ..., 1967, 1963, 1961],
        [1963, 1962, 1970, ..., 1968, 1967, 1967],
        [1966, 1969, 1964, ..., 1967, 1964, 1964]],

       [[1928, 1925, 1931, ..., 1928, 1930, 1930],
        [1925, 1927, 1929, ..., 1934, 1926, 1926],
        [1934, 1927, 1932, ..., 1926, 1933, 1928],
        ...,
        [1933, 1925, 1926, ..., 1925, 1931, 1926],
        [1929, 1932, 1934, ..., 1929, 1929, 1925],
        [1934, 1933, 1927, ..., 1925, 1932, 1925]],

       ...,

       [[  10,    5,   1

In [13]:
%timeit -n 10 a = 2

for i in np.array(np.nditer(Z)):
    i += 1
Z

32.9 ns ± 7 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[   9,    7,    7, ...,    6,   10,    6],
        [   6,    4,    7, ...,    7,   10,   10],
        [  11,    5,    4, ...,   11,    9,    9],
        ...,
        [   3,    4,    2, ...,   11,    3,    7],
        [   2,    6,    7, ...,   11,    9,   11],
        [  11,    2,    2, ...,    8,    3,    2]],

       [[1967, 1962, 1969, ..., 1965, 1963, 1967],
        [1960, 1961, 1966, ..., 1966, 1960, 1963],
        [1965, 1964, 1966, ..., 1965, 1962, 1964],
        ...,
        [1960, 1966, 1965, ..., 1966, 1962, 1960],
        [1962, 1961, 1969, ..., 1967, 1966, 1966],
        [1965, 1968, 1963, ..., 1966, 1963, 1963]],

       [[1927, 1924, 1930, ..., 1927, 1929, 1929],
        [1924, 1926, 1928, ..., 1933, 1925, 1925],
        [1933, 1926, 1931, ..., 1925, 1932, 1927],
        ...,
        [1932, 1924, 1925, ..., 1924, 1930, 1925],
        [1928, 1931, 1933, ..., 1928, 1928, 1924],
        [1933, 1932, 1926, ..., 1924, 1931, 1924]],

       ...,

       [[   9,    4,   1

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [16]:

Z = np.random.randint(0,10,50)
print(Z)


[7 7 4 4 5 8 7 9 1 3 9 5 0 0 8 6 4 4 0 8 1 6 0 6 8 3 0 6 9 2 1 0 6 6 2 4 1
 6 8 5 1 9 4 9 5 2 5 9 2 5]


In [17]:
rint = np.argmax(np.bincount(Z))
rint

6

In [19]:
np.where(Z==rint)

(array([15, 21, 23, 27, 32, 33, 37], dtype=int64),)

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [14]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[9, 1, 2, 5, 2, 3]
[9, 1, 2, 5, 2, 3]
[[9, 7, 0, 9], [5, 7, 6, 7], [9, 5, 9, 1]]
[array([9, 7, 0, 9]), array([5, 7, 6, 7]), array([9, 5, 9, 1])]
[[[9, 0], [6, 2], [8, 2]], [[6, 6], [3, 5], [3, 0]]]
[array([[9, 0],
       [6, 2],
       [8, 2]]), array([[6, 6],
       [3, 5],
       [3, 0]])]


In [ ]:
'''
Your Code
'''